name: frontend
description: "CAO - Find a place to go"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  phosphor_flutter: ^2.1.0
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # HTTP
  http: ^1.2.0

  # Local storage (token)
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/cao_logo.png
    - lib/assets/food.png
    - lib/assets/forest.png
    - lib/assets/bar.png
    - lib/assets/hotel.png
    - lib/assets/cafe.png
    - lib/assets/holiday.png